YUNIKORN-466: Node capacity update does not update root queue or partition
apache/incubator-yunikorn-core pull request #229
Opened 2020-12-10 16:12 UTC by manirajv06

Added updateNode in Partition object to update the partition resource and root queue resource whenever node resources changes.

2020-12-11 04:54 UTC, wilfred-s requested changes
Can you also add unit test for the newly created method as part of the partition tests?

2020-12-11 04:54 UTC, wilfred-s commented on pkg/scheduler/tests/operation_test.go
> +	err = ms.proxy.Update(&si.UpdateRequest{
We have a node already, we can perform the second part of the test (lowering the resources) using the same node.

2020-12-11 14:20 UTC, manirajv06 commented on pkg/scheduler/partition.go
> +// Update a node
> Can you also add unit test for the newly created method as part of the partition tests?

Added.

2020-12-11 14:21 UTC, manirajv06 commented on pkg/scheduler/partition.go
> +// Update a node
> Explain what you update on the node and why that triggers the partition update etc.

On receiving node update event signal, context#updateNodes calls partition#updateNode() to set the correct value for both partition total resource and root queue max resource.

2021-01-04 03:13 UTC, wilfred-s requested changes
Please see the comments, change is looking good with some minor issues.

2021-01-04 03:13 UTC, wilfred-s commented on pkg/scheduler/tests/operation_test.go
> +		[]string{"node-1:1234"}, 100, 1000)
No need to split the line to keep length down, make it one line. (multiple times found)

2021-02-01 03:55 UTC, closed without merging

2021-02-01 03:55 UTC, wilfred-s approved these changes
conflicts fixed on commit