[YUNIKORN-870] Enhance application-related REST APIs
apache/incubator-yunikorn-core pull request #328
Opened 2021-10-02 09:22 UTC by chia7712

### What is this PR for?
We are integrating yunikorn with monitor system through application REST APIs. The application rest APIs is useful but it lacks three important information.
1. elapsed time of a application
2. the allocations to use when running (the `usedResource` is reset to zero when the application is terminated)
3. user name (It can enable us to trace the application for specific user, but I am fire to remove this if it is a security issue.)
Also, the application REST APIs need to be more flexible. For example, it should support following queries:
1. applicationState
2. user name (will be added)
This issue is related to following REST APIs.
1. `/ws/v1/apps`
2. `/ws/v1/partition/{partition}/queue/{queue}/applications`

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Update web docs of application REST APIs

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-870

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2021-11-11 01:58 UTC, wilfred-s requested changes
Elapsed time feels ambiguous when displayed. It is not possible to tell from the value if the app is still running or not. You need to calculate that info, or combine it with the state field.

Can we not store the `FinishedTime` in the application object instead, which we initialise as Zero time. When we unset the queue we set it to `time.Now()` Then we have multiple things we can do with that we could return the the finished time by itself or return both finished time and total run time. Based on what is set the end user can easily determine what is going on.

2022-02-24 23:51 UTC, wilfred-s commented
@chia7712 any update on this one. We seem to be so close to getting this done.

2022-02-26 10:31 UTC, chia7712 commented
The response of `ws/v1/apps` is shown below.


```json
[
    {
        "applicationID": "spark-513ec7450ab34c81957c7bea0d8c5d2a",
        "usedResource": "[]",
        "maxUsedResource": "[]",
        "partition": "default",
        "queueName": "root.infinite",
        "submissionTime": 1645871481994982370,
        "finishedTime": null,
        "allocations": [],
        "applicationState": "New",
        "user": "nobody"
    },
    {
        "applicationID": "spark-2f6d5babe1dd42478f57d9e965af2411",
        "usedResource": "[memory:0 vcore:0]",
        "maxUsedResource": "[memory:3222 vcore:5000]",
        "partition": "default",
        "queueName": "root.infinite",
        "submissionTime": 1645871347893002178,
        "finishedTime": 1645871391609017573,
        "allocations": [],
        "applicationState": "Completed",
        "user": "nobody"
    }
]
```

The first application has `null` finishedTime since it is not finished.

2022-03-02 17:43 UTC, wilfred-s commented on pkg/scheduler/objects/application.go
> +	finishedTime         *time.Time             // the time of finishing this application. the default value is nil
see comment below

2022-03-02 18:10 UTC, wilfred-s requested changes
I think using the pointer to the int is the correct solution to display the not finished case. I think hiding the conversion in a utility function as part of `common/utils.go` make it more usable in the long run.
Can you also confirm that this works for the new API call path, I checked and it looks like it does just want a confirmation.

2022-03-02 18:10 UTC, wilfred-s commented on pkg/scheduler/objects/application.go
> +func (sa *Application) FinishedTimeInUnixNano() *int64 {
We might want to support this for other time values also.
Can we generalise this into a utility function? Bases on a time object and use time.IsZero():
```
func ZeroTimeInUnixNano(t time.Time) *int64 {
	if t.IsZero() {
		return nil
	}
	tInt := t.UnixNano()
	return &tInt
}
```

2022-03-02 18:12 UTC, wilfred-s commented on pkg/scheduler/objects/application.go
> +func (sa *Application) FinishedTimeInUnixNano() *int64 {
the conversion into the `*int64` can then be made as part of the DAO creation

2022-03-03 07:15 UTC, chia7712 commented
> Can you also confirm that this works for the new API call path, I checked and it looks like it does just want a confirmation.

I have checked related call path, and there is nothing weird.

2022-03-03 23:33 UTC, closed without merging