[YUNIKORN-1054] Add more queue metrics to Yunikorn
apache/incubator-yunikorn-core pull request #367
Opened 2022-02-01 14:52 UTC by pbacsko

### What is this PR for?
Adding more queue metrics to Yunikorn.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1054

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2022-02-01 14:55 UTC, pbacsko commented
Still in WIP. 
Discuss testing & `RMReleaseAllocationEvent.QueueNames`.

2022-02-03 10:52 UTC, wilfred-s requested changes
Can we instead of passing the queue info all the way back up rely on the `partitionContext` code to trigger the queue metrics changes?
Every add and remove will go through the partition and in the partition code we have access to the application and thus the queue. We need to either increase or decrease the allocated resources in the queues on add and remove of the alloc. Check for the `removeNodeAllocation()` and `removeAllocation()` code in the partition context. Inside those we know the number of containers removed as we call `DecAllocatedResource()` with the sum of resources. We thus also know the count.
Similarly we can do the add of allocations.

I think that will simplify the change.

2022-02-03 10:52 UTC, wilfred-s commented on pkg/scheduler/objects/application_state.go
> +				event.Args[0].(*Application).clearStateTimer() //nolint:errcheck
Lets do this consistently:
* Remove all error checks on cast from all callback definitions including the string cast
* Add the nolint comment to all casts 
* Document at the start of the callback declaration the fact that arg 0 must be an app object and arg 1 a string. Doing something different will cause a run time panic.

2022-02-04 12:33 UTC, pbacsko commented
TODO:
* Pending apps per queue
* Killed apps per queue (needed?)

2022-02-18 06:13 UTC, wilfred-s requested changes
One minor nit: unlocked QueuePath access

2022-02-18 06:13 UTC, wilfred-s commented on pkg/scheduler/partition.go
> +			metrics.GetQueueMetrics(queue.QueuePath).IncReleasedContainer()
I think this should be a GetQueuePath() call and not a direct access to the QueuePath

2022-02-24 06:32 UTC, wilfred-s approved these changes
LGTM

2022-02-24 06:35 UTC, closed without merging