[Yunikorn 1093] Track rejected applications
apache/incubator-yunikorn-core pull request #380
Opened 2022-03-06 04:49 UTC by steinsgateted

### What is this PR for?
Display rejected applications information in REST.
### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-1093

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2022-03-06 06:01 UTC, steinsgateted commented
If the app is rejected, display this message in /ws/v1/apps :
```
[
  {
    "applicationID": "application-sleep-0003",
    "usedResource": "[]",
    "maxUsedResource": "[]",
    "partition": "default",
    "queueName": "",
    "submissionTime": 1646541113515060500,
    "finishedTime": 1646541113515105300,
    "allocations": [],
    "applicationState": "Rejected",
    "user": "nobody",
    "rejectionMessage": "failed to place application application-sleep-0003: application rejected: no placment rule matched"
  }
]
```
Because the rejected app was not added to the queue, there is no information in /ws/v1/partition/{partitioName}/queue/{queueName}/applications.

2022-03-08 05:40 UTC, wilfred-s requested changes

2022-03-08 05:40 UTC, wilfred-s commented on pkg/scheduler/context.go
> +			stateChangeErr := partition.addRejectedApplication(rejectedApp, err.Error())
We do not need to store this in a local var, just pass in directly into the call.
Also see comment below around the signature for `addRejectedApplication`

2022-03-08 05:40 UTC, wilfred-s commented on pkg/scheduler/objects/application.go
> +	return sa.rejectionMessage
Should add test coverage, specially when setting the message from the state change

2022-03-08 05:40 UTC, wilfred-s commented on pkg/scheduler/objects/application.go
> +	sa.finishedTime = time.Now()
Add test coverage in `TestFinishedTime()`

2022-03-08 05:40 UTC, wilfred-s commented on pkg/scheduler/partition.go
> +
This is just used once in a test, in the line above in the test we directly check the map. Accessing the map in the test directly should be OK.

2022-03-08 05:40 UTC, wilfred-s commented on pkg/scheduler/partition.go
> +	}
Why are you returning this error? There is nothing that we can do with the error outside of this function. It also looks like it break processing of the message in the calling function.
This change should also never fail. Change this to something like `log.Logger().Warn("BUG: Unexpected failure...` and continue processing. Do not return the error.

NOTE: calling the event system will also call `OnStateChange()` as we enter a new state. That triggers an event to the shim to be created. That event has the wrong info in it as we do not want pass it back as an updated application. We need to filter out RejectApplication state changes.

2022-03-08 05:40 UTC, wilfred-s commented on pkg/scheduler/partition.go
> +	rejectedApplication.SetRejectionMessage(rejectionMessage)
Why do we not wrap this up in the state change call?
You already set the state timer in that call why not add these two to that action.
We also would not need functions to set these values in that case as the application object can not be accessed by anything yet.

2022-03-08 05:40 UTC, wilfred-s commented on pkg/webservice/handlers.go
> +		}
Can we add a test in the `handler_test` to cover this?

2022-03-08 17:01 UTC, steinsgateted commented
Thanks for your explanation.

2022-03-09 03:25 UTC, wilfred-s approved these changes
LGTM
thank you for your contribution

2022-03-09 03:30 UTC, closed without merging